{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rproxy-ui.serviceAccountName" . }}
  labels: {{- include "rproxy-ui.labels" . | nindent 4 }}
# the UI does not use the Kubernetes API (rproxy-gateway writes what it needs into a Secret)
automountServiceAccountToken: false
{{- end }}
